
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import Calculator

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\SCSM11\Desktop\Dev Folder\Python Project\Tkinter-Designer-master\build\assets\frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("277x391")
window.configure(bg = "#474545")

# calculation here
CurrentText = ""
IsCalculated = False
def AddNumber(NumberToAdd):
    global CurrentText
    global IsCalculated

    if IsCalculated and not Calculator.IsSymbol(str(NumberToAdd)):
        CurrentText = ""

    if len(CurrentText) == 0:
        if NumberToAdd == 0 or Calculator.IsSymbol(str(NumberToAdd)):
            return
    else:
        if Calculator.IsSymbol(str(NumberToAdd)) and Calculator.IsSymbol(CurrentText[-1]):
            return

    IsCalculated = False
    CurrentText = CurrentText + str(NumberToAdd)
    updateCanvas()

def RemoveLastCharacter():
    global CurrentText
    global IsCalculated
    if IsCalculated:
        CurrentText = ""
    else:
        CurrentText = CurrentText[0:-1]
    updateCanvas()

def GetCalculationResult():
    global CurrentText
    global IsCalculated
    operators = []
    operands = []
    last_index = 0

    for i, char in enumerate(CurrentText):
        if char in '+-*/':
            operators.append(char)
            operand = CurrentText[last_index:i].strip()
            operands.append(operand)
            last_index = i + 1

    if CurrentText[-1] in '+-*/':
        operands.append(0)
    else:
        operands.append(CurrentText[last_index:].strip())

    if len(operands) <= 1 and len(operators) <= 1:
        return
    else:
        CurrentText = str(Calculator.EvaluateExpression(operators, operands))
        CurrentText = CurrentText[:15]
        IsCalculated = True

    updateCanvas()

def updateCanvas():
    global CurrentText
    canvas.itemconfig(tagOrId=CalculationText, text = CurrentText)

canvas = Canvas(
    window,
    bg = "#474545",
    height = 391,
    width = 277,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    138.0,
    57.0,
    image=image_image_1
)

CalculationText = canvas.create_text(
    30.0,
    42.0,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

button_Number_0_Image = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_Number_0 = Button(
    image=button_Number_0_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(0),
    relief="flat"
)
button_Number_0.place(
    x=83.0,
    y=304.0,
    width=40.0,
    height=40.0
)

button_Number_1_Image = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_Number_1 = Button(
    image=button_Number_1_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(1),
    relief="flat"
)
button_Number_1.place(
    x=15.0,
    y=242.0,
    width=40.0,
    height=40.0
)

button_Number_2_Image = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_Number_2 = Button(
    image=button_Number_2_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(2),
    relief="flat"
)
button_Number_2.place(
    x=83.0,
    y=242.0,
    width=40.0,
    height=40.0
)

button_Number_3_Image = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_Number_3 = Button(
    image=button_Number_3_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(3),
    relief="flat"
)
button_Number_3.place(
    x=152.0,
    y=242.0,
    width=40.0,
    height=40.0
)

button_Number_4_Image = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_Number_4 = Button(
    image=button_Number_4_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(4),
    relief="flat"
)
button_Number_4.place(
    x=15.0,
    y=180.0,
    width=40.0,
    height=40.0
)

button_Number_5_Image = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_Number_5 = Button(
    image=button_Number_5_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(5),
    relief="flat"
)
button_Number_5.place(
    x=83.0,
    y=180.0,
    width=40.0,
    height=40.0
)

button_Number_6_Image = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_Number_6 = Button(
    image=button_Number_6_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(6),
    relief="flat"
)
button_Number_6.place(
    x=152.0,
    y=180.0,
    width=40.0,
    height=40.0
)


button_Number_7_Image = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_Number_7 = Button(
    image=button_Number_7_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(7),
    relief="flat"
)
button_Number_7.place(
    x=15.0,
    y=119.0,
    width=40.0,
    height=40.0
)

button_Number_8_Image = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_Number_8 = Button(
    image=button_Number_8_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(8),
    relief="flat"
)
button_Number_8.place(
    x=83.0,
    y=119.0,
    width=40.0,
    height=40.0
)

button_Number_9_Image = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_Number_9 = Button(
    image=button_Number_9_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber(9),
    relief="flat"
)
button_Number_9.place(
    x=152.0,
    y=119.0,
    width=40.0,
    height=40.0
)

button_Plus_Image = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_Plus = Button(
    image=button_Plus_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber("+"),
    relief="flat"
)
button_Plus.place(
    x=221.0,
    y=180.0,
    width=40.0,
    height=40.0
)


button_Multiply_Image = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_Multiply = Button(
    image=button_Multiply_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber("*"),
    relief="flat"
)
button_Multiply.place(
    x=221.0,
    y=119.0,
    width=40.0,
    height=40.0
)


button_Divide_Image = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_Divide = Button(
    image=button_Divide_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber("/"),
    relief="flat"
)
button_Divide.place(
    x=15.0,
    y=304.0,
    width=40.0,
    height=40.0
)

button_Remove_Image = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_Remove = Button(
    image=button_Remove_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: RemoveLastCharacter(),
    relief="flat"
)
button_Remove.place(
    x=152.0,
    y=304.0,
    width=40.0,
    height=40.0
)

button_Minus_Image = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_Minus = Button(
    image=button_Minus_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: AddNumber("-"),
    relief="flat"
)
button_Minus.place(
    x=221.0,
    y=242.0,
    width=40.0,
    height=40.0
)

button_Calculate_Image = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_Calculate = Button(
    image=button_Calculate_Image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: GetCalculationResult(),
    relief="flat"
)
button_Calculate.place(
    x=221.0,
    y=304.0,
    width=40.0,
    height=40.0
)

#button_Close_Image = PhotoImage(
#    file=relative_to_assets("button_17.png"))
#button_Close = Button(
#    image=button_Close_Image,
#    borderwidth=0,
#    highlightthickness=0,
#    command=lambda: print("button_17 clicked"),
#    relief="flat"
#)
#button_Close.place(
#    x=251.0,
#    y=7.0,
#    width=0.0,
#    height=0.0
#)

#canvas.create_rectangle(
#    253.0,
#    9.0,
#    269.0,
#    25.0,
#    fill="#FFFFFF",
#    outline="")
window.resizable(False, False)
window.mainloop()
